# Generated by Django 4.0 on 2024-08-03 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StudentModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.IntegerField()),
                ('gmail', models.EmailField(max_length=254)),
                ('company', models.CharField(max_length=30)),
                ('phonenumber', models.BigIntegerField()),
                ('dob', models.DateField()),
                ('Gender', models.CharField(max_length=30)),
            ],
        ),
    ]
