# Generated by Django 4.0 on 2024-08-03 10:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='studentmodel',
            old_name='company',
            new_name='state',
        ),
    ]
