# Generated by Django 4.0 on 2024-08-03 10:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0002_rename_company_studentmodel_state'),
    ]

    operations = [
        migrations.RenameField(
            model_name='studentmodel',
            old_name='Gender',
            new_name='gender',
        ),
    ]
