# Generated by Django 4.0 on 2024-08-03 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0003_rename_gender_studentmodel_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentmodel',
            name='phonenumber',
            field=models.IntegerField(),
        ),
    ]
