# Generated by Django 4.0 on 2024-08-03 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0004_alter_studentmodel_phonenumber'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentmodel',
            name='name',
            field=models.CharField(max_length=30),
        ),
    ]
